# Generated by Django 5.2.3 on 2025-06-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_orderproduct_product_order_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('H', 'Herramientas'), ('S', 'Seguridad'), ('M', 'Materiales')], default='H', max_length=1),
            preserve_default=False,
        ),
    ]
